### PR TITLE
Fix: Synchronize position deletion in PositionsByPoolId

### LINKED ISSUE #143: garbage collect deleted store key for sort
Delete method doesn't sync the deleted position in `PositionsByPoolId`

### PR DESCRIPTION
**Pull request by pri-3x**
## Overview

fix #143
This PR addresses an issue where the `Delete` method did not synchronize the deleted position in the `PositionsByPoolId` store. 

### Changes Made:
- Updated the `RemovePosition` method in the `store_position.go` file to ensure that when a position is deleted from the main store, it is also removed from the corresponding `PositionsByPoolId` store.
- Added logic to retrieve the `PoolId` of the deleted position and delete the position from the pool-specific store.

### Impact:
This change ensures that the state of the positions is consistent across all relevant stores, preventing potential issues with data integrity when querying positions by pool ID after deletions.

### CODE REVIEW

File: x/liquiditypool/keeper/store_position.go [hunk 1]
```diff
@@ -85,6 +85,14 @@ func (k Keeper) RemovePosition(ctx context.Context, id uint64) {
 	storeAdapter := runtime.KVStoreAdapter(k.storeService.OpenKVStore(ctx))
 	store := prefix.NewStore(storeAdapter, types.KeyPrefix(types.PositionKey))
 	store.Delete(GetPositionIDBytes(id))
+
+	// Remove from PositionsByPoolId
+	position, found := k.GetPosition(ctx, id)
```
Comment (kimurayu45z) [inline x/liquiditypool/keeper/store_position.go:90]: If this function is executed after `store.Delete(GetPositionIDBytes(id))`, it would always return `[Empty], false`.

Shouldn't it be like below?

```go
func (k Keeper) RemovePosition(ctx context.Context, id uint64) {
	storeAdapter := runtime.KVStoreAdapter(k.storeService.OpenKVStore(ctx))
	store := prefix.NewStore(storeAdapter, types.KeyPrefix(types.PositionKey))
	store.Delete(GetPositionIDBytes(id))

	k.RemovePositionsByPool(ctx, id)
	k.RemovePositionsByAddress(ctx, id)
}
```

```go
// Remove PositionBy Pool
func RemovePositionsByPool(...) {
  store = prefix.NewStore(storeAdapter, types.PositionByPoolPrefix(poolId))
  iterator := storetypes.KVStorePrefixIterator(store, []byte{})
  defer iterator.Close()

  for ; iterator.Valid(); iterator.Next() {
    id := sdk.BigEndianToUint64(iterator.Value())
    store.Delete(iterator.Value())
  }
}
// Remove PositionsByAddress
func RemovePositionsByAddress(...) {
  // Do similar things
}
```

**Review by kimurayu45z — CHANGES_REQUESTED** [review]

**Comment by kimurayu45z** [comment]
Thank you for submitting a Pull Request, I appreciate it!
Please check the review comment.

**Comment by pri-3x** [comment]
> Thank you for submitting a Pull Request, I appreciate it! Please check the review comment.

Thanks for the feedback, can you review again?

**Comment by kimurayu45z** [comment]
Thank you for revision!
I will merge this PR, and I will fix slight remaining parts.

**Review by kimurayu45z — APPROVED** [review]

**Comment by pri-3x** [comment]
@kimurayu45z Thankyou :)
Would you be willing to share your email or preferred professional contact method please?

**Comment by kimurayu45z** [comment]
Contact me in Discord of Sunrise server.
https://discord.com/invite/sunrise
